
###
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "nombreUsuario" : "prueba7",
    "nombre" : "prueba7",
    "password" : "123",
    "correo" : "prueba7@example.com",
    "telefono" : "00000000",
    "idRol" : 4 ,
    "ci" : "0000000",
    "tipoUsuario" : "empleado"
}

###
PATCH http://localhost:3000/user/editarUsuario/5
Content-Type: application/json

{    
"nombre": "marta rodriguez",
"nombreUsuario": "marta",
"password": "123",
"telefono": "71267273"
}

###
GET http://localhost:3000/user/verUsuarios

### 
GET http://localhost:3000/productos/mostrar?tipo

###
GET http://localhost:3000/user/ed

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    // --cuenta admin--
    "nombreUsuario": "marta321",	
    "password": "123"
} 

###
GET http://localhost:3000/auth/verificar

###
GET http://localhost:3000/auth/logout

### 
GET http://localhost:3000/admin/panelAdministrativo

### 
GET http://localhost:3000/menus/todos

### 
GET http://localhost:3000/menus/dia/Lunes

### 
PATCH http://localhost:3000/menus/eliminar/1

### 
PATCH http://localhost:3000/menus/editar/1
Content-Type: application/json

{
     "dia": "Martes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]
           
  
}

### 
POST http://localhost:3000/menus/crear
Content-Type: application/json

{
     "dia": "Lunes",
     "productos": [
        {"id": 2},
        {"id": 3}
     ]
           
  
}

### Crear nuevo rol
POST http://localhost:3000/roles/crear
Content-Type: application/json

{
    "nombre": "p"
}

### Editar rol
Put http://localhost:3000/roles/editar
Content-Type: application/json

{
    
        "oldRol": "cardiologo2",
        "newRol": "cardiologo_principal"
    
}

### Eliminar rol por ID
DELETE http://localhost:3000/roles/eliminar/3

### roles y permisos
GET http://localhost:3000/roles/permisos

### permisos de un rol
GET http://localhost:3000/roles/permisos/2

### crear permiso
POST http://localhost:3000/permisos/crear
Content-Type: application/json

{
  "descripcion": "Nuevo4"
}

### Editar permiso
Put http://localhost:3000/permisos/editar
Content-Type: application/json

{
  "idPermiso": 8,
    "newDescripcion": "p2"
}

### Eliminar permiso
DELETE http://localhost:3000/permisos/eliminar/6


###  
GET http://localhost:3000/menus/dia/Lunes

### ASIGNAR PERMISO A ROL
POST http://localhost:3000/permisos/asignar
Content-Type: application/json


{
  "idRol": 9,
  "idPermiso": 5
}

### Agregar stock
POST http://localhost:3000/inventario/agregar
Content-Type: application/json

{
  "descripcion": "nuevo producto2",
  "stockActual": 100,
  "stockMinimo": 5
}

### Editar stock o actualizar stock (Disminuir)
PUT http://localhost:3000/inventario/actualizar
Content-Type: application/json

{
  "id": 34,
  "nuevoStockActual": 200,
  "nuevoStockMinimo": 20
}


### registrar reserva
POST http://localhost:3000/reservas/crear
Content-Type: application/json

{
  "idMesa": 4,
  "fecha": "2025-05-27",
  "hora": "12:00:00",
  "idClienteWeb": 4,
  "idEstado": 7
}

###
POST http://localhost:3000/reservas/mesas
Content-Type: application/json

{
  "fecha": "2025-05-27",
  "hora": "12:00:00"
}

### Actualizar reserva (Editar reserva)
PUT http://localhost:3000/reservas/editar
Content-Type: application/json

{
  "id": 4,
  "fecha": "2023-12-20",
  "hora": "15:00",
  "idClienteWeb": 4,
  "idEstado": 6
}

### Cancelar reserva
DELETE http://localhost:3000/reservas/eliminar/6
Content-Type: application/json

### Mostrar reservas
GET http://localhost:3000/reservas/mostrar

### Mostrar reservas por nombre de cliente
GET http://localhost:3000/reservas/mostrar/juan p rez
### 
GET http://localhost:3000/inventario/mostrarStock/15

###
GET http://localhost:3000/productos/obtener?tipo=3

/// ****registrar pedido ****
### 
POST http://localhost:3000/pedido/registrar/3
Content-Type: application/json

{
     "mesas": [
        {"id": 1},
        {"id": 2}
     ],

     "productos": 
        [{
        "id": 2,
        "cantidad": 2,
        "precio": 6,
        "exclusiones": 
            [
             {"idIngrediente": 1},
             {"idIngrediente": 2}
            ]
        },
        {
        "id": 3,
        "cantidad": 1,
        "precio": 6,
        "exclusiones": 
            [
             
            ]
        }
        ]
}        
        
// Visualizar pedidos pendientes, para el cocinero


### registrar ingrediente
POST http://localhost:3000/ingredientes/crear
Content-Type: application/json

{
  "nombre": "p2",
  "idUnidadMedida": 1,
  "idStock": 1,
  "idEstado": 1
}
### editar ingrediente --> falta corregir
PUT http://localhost:3000/ingredientes/editar
Content-Type: application/json

{
  "id": 20,
  "nombre": "nuevo ingrediente2",
  "idUnidadMedida": 3,
  "idStock": 50,
  "idStado": 13
}

### eliminar ingrediente
DELETE http://localhost:3000/ingredientes/eliminar/20

### mostrar ingredientes
GET http://localhost:3000/ingredientes/mostrar

### mostrar ingredientes id
GET http://localhost:3000/ingredientes/mostrar/1

### crear Receta
POST http://localhost:3000/recetas/crear
Content-Type: application/json

{
  "idProducto": 4,
  "idIngrediente": 21,
  "cantidad": 9
}

=======
}

### registrar ingrediente
POST http://localhost:3000/ingredientes/crear
Content-Type: application/json

{
  "nombre": "p2",
  "idUnidadMedida": 1,
  "idStock": 1,
  "idEstado": 1
}
### editar ingrediente --> falta corregir
PUT http://localhost:3000/ingredientes/editar
Content-Type: application/json

{
  "id": 20,
  "nombre": "nuevo ingrediente2",
  "idUnidadMedida": 3,
  "idStock": 50,
  "idStado": 13
}

### eliminar ingrediente
DELETE http://localhost:3000/ingredientes/eliminar/20

### mostrar ingredientes
GET http://localhost:3000/ingredientes/mostrar

### mostrar ingredientes id
GET http://localhost:3000/ingredientes/mostrar/1

### crear Receta
POST http://localhost:3000/recetas/crear
Content-Type: application/json

{
  "idProducto": 4,
  "idIngrediente": 21,
  "cantidad": 9
}


### editar receta --> corregir
PUT http://localhost:3000/recetas/editar
Content-Type: application/json

{
  "idProducto": 4,
  "idIngrediente": 21,
  "cantidad": 50
}
### eliminar receta
DELETE http://localhost:3000/recetas/eliminar
Content-Type: application/json

{
  "idProducto": 4,
  "idIngrediente": 21
}

### mostrar recetas
GET http://localhost:3000/recetas/mostrar/1

### crear Producto --> falta corregir
POST http://localhost:3000/productos/crear
Content-Type: application/json

{
  "nombre": "nuevo producto",
  "precio": 10,
  "descripcion": "nuevo producto de prueba",
  "time": "00:10:00",
  "idCategoria": 1,
  "idStock": 1
}

### editar producto --> falta corregir
PUT http://localhost:3000/productos/editar
Content-Type: application/json

{
  "id": 24,
  "nombre": "nuevo producto",
  "precio": 10,
  "descripcion": "nuevo producto de prueba",
  "time": 10,
  "idCategoria": 1,
  "idStock": 1
}

### eliminar producto --> falta corregir
DELETE http://localhost:3000/productos/eliminar/24

### mostrar productos
GET http://localhost:3000/productos/mostrar

### mostrar productos por id
GET http://localhost:3000/productos/mostrar/1
### 
GET http://localhost:3000/pedido/pendientes

### 
GET http://localhost:3000/pedido/cliente/5

